# Generated by Django
import uuid
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_bases',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kb', models.ForeignKey(db_column='kb_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.knowledgebase')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=500)),
                ('storage_path', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='uploading', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata_', models.JSONField(blank=True, db_column='metadata', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb', models.ForeignKey(db_column='kb_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.knowledgebase')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, null=True)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('chunk_metadata', models.JSONField(blank=True, db_column='metadata', default=dict)),
                ('status', models.CharField(default='active', max_length=50)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='app.document')),
                ('kb', models.ForeignKey(db_column='kb_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='app.knowledgebase')),
            ],
            options={
                'db_table': 'chunks',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('cited_chunk_ids', models.JSONField(blank=True, default=list)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.conversation')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
