# Generated by Django 6.0.7 on 2026-07-16 02:49

import pgvector.django.vector
from django.db import migrations, models


def clear_existing_embeddings(apps, schema_editor):
    """Clear all existing embeddings so we can resize the vector column."""
    Chunk = apps.get_model('app', 'Chunk')
    Chunk.objects.all().update(embedding=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # Step 1: Clear all existing embeddings (they were 768-dimensional)
        migrations.RunPython(clear_existing_embeddings, migrations.RunPython.noop),

        # Step 2: Resize the vector column to 3072 dimensions
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
